name: bigquery

on:
  schedule:
    - cron: '07 02 * * MON-FRI'   # Ejecutar a las 18:15 de lunes a viernes

jobs:
  ejecutar-script-de-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Instalar dependencias
        run: |
          pip install pandas google-auth pandas-gbq gcsfs

      - name: Crear archivo JSON con secreto
        run: |
          echo '{"GCP_BUCKET": "${{ secrets.GCP_BUCKET }}"}' > secret.json

      - name: Ejecutar script de Python
        run: |
          python Automatizado.py

      - name: Guardar archivo JSON como artefacto
        uses: actions/upload-artifact@v2
        with:
          name: secret
          path: secret.json
