name: Actualizar Dato

on:
  schedule:
    - cron: '28 02 * * MON-FRI'   # Ejecutar a las 08:00 de lunes a viernes

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Instalar dependencias
      run: |
        pip install pandas azure-storage-blob fastparquet pyarrow

    - name: Ejecutar script de Python
      run: |
        python test.py
